name: "Release Published to Discord"
on:
  release:
    types: [published]

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x gradlew
      
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          TAG: ${{ github.event.release.tag_name }}
        run: ./gradlew publish
  
  notify-discord:
    runs-on: ubuntu-latest
    needs: publish-maven
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Notify Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "3371747"
          username: "NoctisUI Release"
          avatar_url: "https://raw.githubusercontent.com/Libnaus/.github/refs/heads/main/profile/assets/img/logo.png"
          footer_title: "NoctisUI Release ${{ github.event.release.tag_name }}"
          footer_icon: "https://raw.githubusercontent.com/Libnaus/.github/refs/heads/main/profile/assets/img/logo.png"
          footer_timestamp: true
          reduce_headings: true